# Generated by Django 3.2.25 on 2024-05-01 01:36

from django.db import migrations, models
import location.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Capital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=256, verbose_name='Страна')),
                ('city', models.CharField(max_length=256, verbose_name='Город')),
                ('geometry', models.JSONField(validators=[location.validators.validate_geometry], verbose_name='Геометрия')),
            ],
            options={
                'verbose_name': 'Столица',
                'verbose_name_plural': 'Столицы',
                'ordering': ('country',),
            },
        ),
        migrations.AddConstraint(
            model_name='capital',
            constraint=models.UniqueConstraint(fields=('country', 'city'), name='unique_country_city'),
        ),
    ]
