version: '3.3'

volumes:
  pg_data:

services:
  db:
    image: postgres:13-alpine
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data
    ports:
      - '5432:5432'
  backend:
    build: ./project/
    env_file: .env
    ports:
      - '8000:8000'
    depends_on:
      - db
